# file: C:\Users\dsuth\AppData\Roaming\Python\Python312\site-packages\h11\_util.py
# hypothesis_version: 6.137.1

[400, 'LocalProtocolError', 'ProtocolError', 'RemoteProtocolError', 'Sentinel', '_T_Sentinel', 'ascii', 'bytesify', 'malformed data', 'validate']