# file: C:\Users\dsuth\AppData\Roaming\Python\Python312\site-packages\email_validator\exceptions_types.py
# hypothesis_version: 6.137.1

[')', ',', 'ValidatedEmail(', 'ascii_domain', 'ascii_email', 'ascii_local_part', 'domain', 'domain_address', 'domain_i18n', 'email', 'email_ascii', 'local', 'local_part', 'mx', 'mx-fallback', 'mx_fallback_type', 'normalized', 'original_email', 'smtputf8']