# file: C:\Users\dsuth\AppData\Roaming\Python\Python312\site-packages\socketio\exceptions.py
# hypothesis_version: 6.137.1

['data', 'message']